/**
 * Autogenerated by Thrift
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 */
#include "image_download_queue_constants.h"



const image_download_queueConstants g_image_download_queue_constants;

image_download_queueConstants::image_download_queueConstants() {
}



