// This autogenerated skeleton file illustrates how to build a server.
// You should copy it to another filename to avoid overwriting it.

#include "ImageDownloadQueue.h"
#include <protocol/TBinaryProtocol.h>
#include <server/TSimpleServer.h>
#include <transport/TServerSocket.h>
#include <transport/TBufferTransports.h>

using namespace apache::thrift;
using namespace apache::thrift::protocol;
using namespace apache::thrift::transport;
using namespace apache::thrift::server;

using boost::shared_ptr;

class ImageDownloadQueueHandler : virtual public ImageDownloadQueueIf {
 public:
  ImageDownloadQueueHandler() {
    // Your initialization goes here
  }

  void dequeue(std::vector<ImageWorkUnit> & _return) {
    // Your implementation goes here
    printf("dequeue\n");
  }

  void enqueue(const std::vector<ImageWorkUnit> & units) {
    // Your implementation goes here
    printf("enqueue\n");
  }

};

int main(int argc, char **argv) {
  int port = 9090;
  shared_ptr<ImageDownloadQueueHandler> handler(new ImageDownloadQueueHandler());
  shared_ptr<TProcessor> processor(new ImageDownloadQueueProcessor(handler));
  shared_ptr<TServerTransport> serverTransport(new TServerSocket(port));
  shared_ptr<TTransportFactory> transportFactory(new TBufferedTransportFactory());
  shared_ptr<TProtocolFactory> protocolFactory(new TBinaryProtocolFactory());

  TSimpleServer server(processor, serverTransport, transportFactory, protocolFactory);
  server.serve();
  return 0;
}

