/**
 * Autogenerated by Thrift
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 */
#ifndef ImageDownloadQueue_H
#define ImageDownloadQueue_H

#include <TProcessor.h>
#include "image_download_queue_types.h"



class ImageDownloadQueueIf {
 public:
  virtual ~ImageDownloadQueueIf() {}
  virtual void dequeue(std::vector<ImageWorkUnit> & _return) = 0;
  virtual void enqueue(const std::vector<ImageWorkUnit> & units) = 0;
};

class ImageDownloadQueueNull : virtual public ImageDownloadQueueIf {
 public:
  virtual ~ImageDownloadQueueNull() {}
  void dequeue(std::vector<ImageWorkUnit> & /* _return */) {
    return;
  }
  void enqueue(const std::vector<ImageWorkUnit> & /* units */) {
    return;
  }
};

class ImageDownloadQueue_dequeue_args {
 public:

  ImageDownloadQueue_dequeue_args() {
  }

  virtual ~ImageDownloadQueue_dequeue_args() throw() {}


  bool operator == (const ImageDownloadQueue_dequeue_args & /* rhs */) const
  {
    return true;
  }
  bool operator != (const ImageDownloadQueue_dequeue_args &rhs) const {
    return !(*this == rhs);
  }

  bool operator < (const ImageDownloadQueue_dequeue_args & ) const;

  uint32_t read(apache::thrift::protocol::TProtocol* iprot);
  uint32_t write(apache::thrift::protocol::TProtocol* oprot) const;

};

class ImageDownloadQueue_dequeue_pargs {
 public:


  virtual ~ImageDownloadQueue_dequeue_pargs() throw() {}


  uint32_t write(apache::thrift::protocol::TProtocol* oprot) const;

};

class ImageDownloadQueue_dequeue_result {
 public:

  ImageDownloadQueue_dequeue_result() {
  }

  virtual ~ImageDownloadQueue_dequeue_result() throw() {}

  std::vector<ImageWorkUnit>  success;

  struct __isset {
    __isset() : success(false) {}
    bool success;
  } __isset;

  bool operator == (const ImageDownloadQueue_dequeue_result & rhs) const
  {
    if (!(success == rhs.success))
      return false;
    return true;
  }
  bool operator != (const ImageDownloadQueue_dequeue_result &rhs) const {
    return !(*this == rhs);
  }

  bool operator < (const ImageDownloadQueue_dequeue_result & ) const;

  uint32_t read(apache::thrift::protocol::TProtocol* iprot);
  uint32_t write(apache::thrift::protocol::TProtocol* oprot) const;

};

class ImageDownloadQueue_dequeue_presult {
 public:


  virtual ~ImageDownloadQueue_dequeue_presult() throw() {}

  std::vector<ImageWorkUnit> * success;

  struct __isset {
    __isset() : success(false) {}
    bool success;
  } __isset;

  uint32_t read(apache::thrift::protocol::TProtocol* iprot);

};

class ImageDownloadQueue_enqueue_args {
 public:

  ImageDownloadQueue_enqueue_args() {
  }

  virtual ~ImageDownloadQueue_enqueue_args() throw() {}

  std::vector<ImageWorkUnit>  units;

  struct __isset {
    __isset() : units(false) {}
    bool units;
  } __isset;

  bool operator == (const ImageDownloadQueue_enqueue_args & rhs) const
  {
    if (!(units == rhs.units))
      return false;
    return true;
  }
  bool operator != (const ImageDownloadQueue_enqueue_args &rhs) const {
    return !(*this == rhs);
  }

  bool operator < (const ImageDownloadQueue_enqueue_args & ) const;

  uint32_t read(apache::thrift::protocol::TProtocol* iprot);
  uint32_t write(apache::thrift::protocol::TProtocol* oprot) const;

};

class ImageDownloadQueue_enqueue_pargs {
 public:


  virtual ~ImageDownloadQueue_enqueue_pargs() throw() {}

  const std::vector<ImageWorkUnit> * units;

  uint32_t write(apache::thrift::protocol::TProtocol* oprot) const;

};

class ImageDownloadQueue_enqueue_result {
 public:

  ImageDownloadQueue_enqueue_result() {
  }

  virtual ~ImageDownloadQueue_enqueue_result() throw() {}


  bool operator == (const ImageDownloadQueue_enqueue_result & /* rhs */) const
  {
    return true;
  }
  bool operator != (const ImageDownloadQueue_enqueue_result &rhs) const {
    return !(*this == rhs);
  }

  bool operator < (const ImageDownloadQueue_enqueue_result & ) const;

  uint32_t read(apache::thrift::protocol::TProtocol* iprot);
  uint32_t write(apache::thrift::protocol::TProtocol* oprot) const;

};

class ImageDownloadQueue_enqueue_presult {
 public:


  virtual ~ImageDownloadQueue_enqueue_presult() throw() {}


  uint32_t read(apache::thrift::protocol::TProtocol* iprot);

};

class ImageDownloadQueueClient : virtual public ImageDownloadQueueIf {
 public:
  ImageDownloadQueueClient(boost::shared_ptr<apache::thrift::protocol::TProtocol> prot) :
    piprot_(prot),
    poprot_(prot) {
    iprot_ = prot.get();
    oprot_ = prot.get();
  }
  ImageDownloadQueueClient(boost::shared_ptr<apache::thrift::protocol::TProtocol> iprot, boost::shared_ptr<apache::thrift::protocol::TProtocol> oprot) :
    piprot_(iprot),
    poprot_(oprot) {
    iprot_ = iprot.get();
    oprot_ = oprot.get();
  }
  boost::shared_ptr<apache::thrift::protocol::TProtocol> getInputProtocol() {
    return piprot_;
  }
  boost::shared_ptr<apache::thrift::protocol::TProtocol> getOutputProtocol() {
    return poprot_;
  }
  void dequeue(std::vector<ImageWorkUnit> & _return);
  void send_dequeue();
  void recv_dequeue(std::vector<ImageWorkUnit> & _return);
  void enqueue(const std::vector<ImageWorkUnit> & units);
  void send_enqueue(const std::vector<ImageWorkUnit> & units);
  void recv_enqueue();
 protected:
  boost::shared_ptr<apache::thrift::protocol::TProtocol> piprot_;
  boost::shared_ptr<apache::thrift::protocol::TProtocol> poprot_;
  apache::thrift::protocol::TProtocol* iprot_;
  apache::thrift::protocol::TProtocol* oprot_;
};

class ImageDownloadQueueProcessor : virtual public apache::thrift::TProcessor {
 protected:
  boost::shared_ptr<ImageDownloadQueueIf> iface_;
  virtual bool process_fn(apache::thrift::protocol::TProtocol* iprot, apache::thrift::protocol::TProtocol* oprot, std::string& fname, int32_t seqid);
 private:
  std::map<std::string, void (ImageDownloadQueueProcessor::*)(int32_t, apache::thrift::protocol::TProtocol*, apache::thrift::protocol::TProtocol*)> processMap_;
  void process_dequeue(int32_t seqid, apache::thrift::protocol::TProtocol* iprot, apache::thrift::protocol::TProtocol* oprot);
  void process_enqueue(int32_t seqid, apache::thrift::protocol::TProtocol* iprot, apache::thrift::protocol::TProtocol* oprot);
 public:
  ImageDownloadQueueProcessor(boost::shared_ptr<ImageDownloadQueueIf> iface) :
    iface_(iface) {
    processMap_["dequeue"] = &ImageDownloadQueueProcessor::process_dequeue;
    processMap_["enqueue"] = &ImageDownloadQueueProcessor::process_enqueue;
  }

  virtual bool process(boost::shared_ptr<apache::thrift::protocol::TProtocol> piprot, boost::shared_ptr<apache::thrift::protocol::TProtocol> poprot);
  virtual ~ImageDownloadQueueProcessor() {}
};

class ImageDownloadQueueMultiface : virtual public ImageDownloadQueueIf {
 public:
  ImageDownloadQueueMultiface(std::vector<boost::shared_ptr<ImageDownloadQueueIf> >& ifaces) : ifaces_(ifaces) {
  }
  virtual ~ImageDownloadQueueMultiface() {}
 protected:
  std::vector<boost::shared_ptr<ImageDownloadQueueIf> > ifaces_;
  ImageDownloadQueueMultiface() {}
  void add(boost::shared_ptr<ImageDownloadQueueIf> iface) {
    ifaces_.push_back(iface);
  }
 public:
  void dequeue(std::vector<ImageWorkUnit> & _return) {
    uint32_t sz = ifaces_.size();
    for (uint32_t i = 0; i < sz; ++i) {
      if (i == sz - 1) {
        ifaces_[i]->dequeue(_return);
        return;
      } else {
        ifaces_[i]->dequeue(_return);
      }
    }
  }

  void enqueue(const std::vector<ImageWorkUnit> & units) {
    uint32_t sz = ifaces_.size();
    for (uint32_t i = 0; i < sz; ++i) {
      ifaces_[i]->enqueue(units);
    }
  }

};



#endif
