/**
 * Autogenerated by Thrift
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 */
#ifndef image_download_queue_CONSTANTS_H
#define image_download_queue_CONSTANTS_H

#include "image_download_queue_types.h"



class image_download_queueConstants {
 public:
  image_download_queueConstants();

};

extern const image_download_queueConstants g_image_download_queue_constants;



#endif
