/**
 * Autogenerated by Thrift
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 */
#ifndef image_download_queue_TYPES_H
#define image_download_queue_TYPES_H

#include <Thrift.h>
#include <protocol/TProtocol.h>
#include <transport/TTransport.h>





class ImageWorkUnit {
 public:

  static const char* ascii_fingerprint; // = "343DA57F446177400B333DC49B037B0C";
  static const uint8_t binary_fingerprint[16]; // = {0x34,0x3D,0xA5,0x7F,0x44,0x61,0x77,0x40,0x0B,0x33,0x3D,0xC4,0x9B,0x03,0x7B,0x0C};

  ImageWorkUnit() : bucket(""), link(""), desired_size(0) {
  }

  virtual ~ImageWorkUnit() throw() {}

  std::string bucket;
  std::string link;
  int32_t desired_size;

  struct __isset {
    __isset() : bucket(false), link(false), desired_size(false) {}
    bool bucket;
    bool link;
    bool desired_size;
  } __isset;

  bool operator == (const ImageWorkUnit & rhs) const
  {
    if (!(bucket == rhs.bucket))
      return false;
    if (!(link == rhs.link))
      return false;
    if (!(desired_size == rhs.desired_size))
      return false;
    return true;
  }
  bool operator != (const ImageWorkUnit &rhs) const {
    return !(*this == rhs);
  }

  bool operator < (const ImageWorkUnit & ) const;

  uint32_t read(apache::thrift::protocol::TProtocol* iprot);
  uint32_t write(apache::thrift::protocol::TProtocol* oprot) const;

};



#endif
