/**
 * Autogenerated by Thrift
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 */
#ifndef page_parse_queue_CONSTANTS_H
#define page_parse_queue_CONSTANTS_H

#include "page_parse_queue_types.h"



class page_parse_queueConstants {
 public:
  page_parse_queueConstants();

};

extern const page_parse_queueConstants g_page_parse_queue_constants;



#endif
