/**
 * Autogenerated by Thrift
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 */
#include "page_parse_queue_constants.h"



const page_parse_queueConstants g_page_parse_queue_constants;

page_parse_queueConstants::page_parse_queueConstants() {
}



