/**
 * Autogenerated by Thrift
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 */
#include "wiki_distance_calculator_constants.h"



const wiki_distance_calculatorConstants g_wiki_distance_calculator_constants;

wiki_distance_calculatorConstants::wiki_distance_calculatorConstants() {
}



