/**
 * Autogenerated by Thrift
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 */
#ifndef wiki_distance_calculator_CONSTANTS_H
#define wiki_distance_calculator_CONSTANTS_H

#include "wiki_distance_calculator_types.h"



class wiki_distance_calculatorConstants {
 public:
  wiki_distance_calculatorConstants();

};

extern const wiki_distance_calculatorConstants g_wiki_distance_calculator_constants;



#endif
