// This autogenerated skeleton file illustrates how to build a server.
// You should copy it to another filename to avoid overwriting it.

#include "WikiDistanceCalculator.h"
#include <protocol/TBinaryProtocol.h>
#include <server/TSimpleServer.h>
#include <transport/TServerSocket.h>
#include <transport/TBufferTransports.h>

using namespace apache::thrift;
using namespace apache::thrift::protocol;
using namespace apache::thrift::transport;
using namespace apache::thrift::server;

using boost::shared_ptr;

class WikiDistanceCalculatorHandler : virtual public WikiDistanceCalculatorIf {
 public:
  WikiDistanceCalculatorHandler() {
    // Your initialization goes here
  }

  void distances(std::vector<WikiDistance> & _return, const std::vector<std::string> & tuples) {
    // Your implementation goes here
    printf("distances\n");
  }

  void page_chain(std::vector<std::string> & _return, const std::string& first, const std::string& second) {
    // Your implementation goes here
    printf("page_chain\n");
  }

};

int main(int argc, char **argv) {
  int port = 9090;
  shared_ptr<WikiDistanceCalculatorHandler> handler(new WikiDistanceCalculatorHandler());
  shared_ptr<TProcessor> processor(new WikiDistanceCalculatorProcessor(handler));
  shared_ptr<TServerTransport> serverTransport(new TServerSocket(port));
  shared_ptr<TTransportFactory> transportFactory(new TBufferedTransportFactory());
  shared_ptr<TProtocolFactory> protocolFactory(new TBinaryProtocolFactory());

  TSimpleServer server(processor, serverTransport, transportFactory, protocolFactory);
  server.serve();
  return 0;
}

