/**
 * Autogenerated by Thrift
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 */
#ifndef site_relationships_TYPES_H
#define site_relationships_TYPES_H

#include <Thrift.h>
#include <protocol/TProtocol.h>
#include <transport/TTransport.h>





class SiteRelationship {
 public:

  static const char* ascii_fingerprint; // = "3E7765496BCF0063C35428E22F902724";
  static const uint8_t binary_fingerprint[16]; // = {0x3E,0x77,0x65,0x49,0x6B,0xCF,0x00,0x63,0xC3,0x54,0x28,0xE2,0x2F,0x90,0x27,0x24};

  SiteRelationship() : first(0), second(0), distance(0) {
  }

  virtual ~SiteRelationship() throw() {}

  int32_t first;
  int32_t second;
  int16_t distance;

  struct __isset {
    __isset() : first(false), second(false), distance(false) {}
    bool first;
    bool second;
    bool distance;
  } __isset;

  bool operator == (const SiteRelationship & rhs) const
  {
    if (!(first == rhs.first))
      return false;
    if (!(second == rhs.second))
      return false;
    if (!(distance == rhs.distance))
      return false;
    return true;
  }
  bool operator != (const SiteRelationship &rhs) const {
    return !(*this == rhs);
  }

  bool operator < (const SiteRelationship & ) const;

  uint32_t read(apache::thrift::protocol::TProtocol* iprot);
  uint32_t write(apache::thrift::protocol::TProtocol* oprot) const;

};



#endif
