/**
 * Autogenerated by Thrift
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 */
#ifndef site_relationships_CONSTANTS_H
#define site_relationships_CONSTANTS_H

#include "site_relationships_types.h"



class site_relationshipsConstants {
 public:
  site_relationshipsConstants();

};

extern const site_relationshipsConstants g_site_relationships_constants;



#endif
