/**
 * Autogenerated by Thrift
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 */
#include "site_relationships_constants.h"



const site_relationshipsConstants g_site_relationships_constants;

site_relationshipsConstants::site_relationshipsConstants() {
}



